version: '3.3'

services:
  webhookgail:
    image: desoldocker/webhookgail
    container_name: axia-data-orbit-testing
    ports:
      - "8085:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=172.16.64.77;Port=5433;Database=AXIA;Username=ado-user;Password=D3s0l#D3s4r0ll0%2024
      - AppSettings__SendTemplateURI=https://cloud01.desol.cloud:2443/api/webhook
      - AppSettings__ApiToken=z0rBmlijawZCwA7HLhZtxC3gtV8goUU7
      - AppSettings__WebhookAccessToken=z0rBmlijawZCwA7HLhZtxC3gtV8goUU7
      - AppSettings__RapihogarAPI=https://backend.rapihogar.com.ar/
      - AppSettings__RapihogarTestAPI=https://backedn.rapihogar.com.ar/
      - AppSettings__RapihogarAPIVersion=v1
      - AppSettings__RapihogarClientId=xtE3eJv3P7HIR9zSGf9YvH91ItnWy5RBIFSgPr2A
      - AppSettings__RapihogarClientSecret=sw8nrhwNmm2kNh03ao0plp5485qGfKryM55DXvisGp9XBWXFLFoFI4DHIsdOPiqrFhQMFU0SbZOrgPFFyvsEDwrurC5Af0K7RcJljZsE5qUDvJZjFSkuYT2Wd4lL8SIV
      - TimeSettings__HourOffset=-3
      - OpenAI__ApiKey=sk-proj-oZp77GxElHkQZ5hxkudgT3BlbkFJ42Y4HElQPDmWJ9nEROr0
      - GailAPI__ApiKey=api-ddd3b3db50ba4c598ac7428cc3e02104-w4og5paWpdgRUZkwbMAKuupZ8-RH_tRpgSGCa_N3uZ4
      - GailAPI__Endpoint=https://api.lula.com
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft=Warning
      - Logging__LogLevel__Microsoft.Hosting.Lifetime=Information
      - Logging__File__Path=logs/WebhookGail.log
      - Logging__File__LogLevel__Default=Debug
      - Logging__File__LogLevel__System=Information
      - Logging__File__LogLevel__Microsoft=Information
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"

volumes:
  portainer_data:
